### ISSUE TITLE
When there is an error in a template ironman won't tell where

### ISSUE THREAD

**Issue by wvides** [ottogiron/ironman#15]
How to replicate
Write a variable with escaped quotes and run the generator

Sample 
`{{.Values.api_name | default \"rest-express-mongo\"}}`

Log without the detail of the file with the syntax error

`There was an error failed to parse template template: ironman:3: unexpected "\\" in operand : template: ironman:3: unexpected "\\" in operand`

**Comment by ottogiron** [comment]
Thank you @omarvides  the message for that error can be improved in this file, and line 

https://github.com/ironman-project/ironman/blob/master/pkg/template/generator.go#L239

Currently, the message is handled with this message

```go
if err != nil {
		return nil, errors.Wrapf(err, "failed to parse template %s ", err)
	}
```

It can be changed to something like :

```go
if err != nil {
       return nil, errors.Wrapf(err, "failed to parse template %s %s ", templateResult.path, err)
}
```

The above message includes the file to be processed
